packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^18.3.1"
  react-dom: "^18.3.1"
  "@hookform/resolvers": "^5.2.2"
  react-hook-form: "^7.71.1"
  next-themes: "^0.4.6"
  lucide-react: "^0.563.0"
  "@tanstack/react-query": "^5.90.20"
  recharts: "2.15.4"
  next: "15.1.6"
  hono: "^4.6.3"
  zustand: "^5.0.10"
  zod: "^3.23.8"
  class-variance-authority: "^0.7.1"
  clsx: "^2.1.1"
  cmdk: "^1.1.1"
  date-fns: "^4.1.0"
  embla-carousel-react: "^8.6.0"
  input-otp: "^1.4.2"
  prettier: "^3.8.1"
  turbo: "^2.8.1"
  radix-ui: "^1.4.3"
  typescript: "5.9.3"
  drizzle-orm: "^0.45.1"
  react-resizable-panels: "^4.5.9"
  react-day-picker: "^9.13.0"
  pg: "^8.18.0"
  postgres: "^3.4.8"
  sonner: "^2.0.7"
  vaul: "^1.1.2"
  tailwind-merge: "^3.4.0"
  tw-animate-css: "^1.4.0"
